# qos_override.yaml
/tf_static:
  history: keep_last
  depth: 1
  reliability: reliable
  durability: transient_local
/kitti/velo/pointcloud:
  history: keep_last
  depth: 10
  reliability: reliable
  durability: transient_local
